import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { StarknetProvider } from "@/components/starknet-provider";
import "./globals.css";
import { bowlby_one, poppins, roboto } from "./fonts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${poppins.variable}
         ${bowlby_one.variable} ${roboto.variable} bg-secondary`}
      >
        <StarknetProvider>{children}</StarknetProvider>
      </body>
    </html>
  );
}
